version: '3.9'

services: 
  frontend:
    build: .
    ports:
      - 8080:80
  api:
    image: abdennour/dummy-rest-api-example
    environment:
      ADMIN_PASSWORD: pass123
    ports:
      - 9090:8080
  api-ambassador:
    image: nginx:1.21-alpine
    ports:
     - 9091:80
    volumes:
      - ./.cloudnative/nginx-conf-skip-cors:/etc/nginx/conf.d:ro
